# Generated by Django 4.2.8 on 2023-12-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Years_of_Experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Candidate_job_category',
            field=models.CharField(max_length=50),
        ),
    ]
