# Generated by Django 4.2.8 on 2023-12-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0002_candidate_years_of_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
